### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by reconbot** [tessel/t2-compiler#19]
We have a few different parts of the project.
- [x] The cross compiler: takes a package and version and produces a tarball of the package with a .node compiled to run on the tessel. Current status: Works for some packages and not others.
- [x] The package service. Current status: Using amazon s3, it's great.
- [ ] The status service: Listens to npm for new publishing and determines if it's a package we care about and if we've got a build
- [ ] The build service - automatically builds packages to work on the tessel as the status service discovers them, and stores them on the package service.
- [ ] The test service? - tries to require packages that are cross built on arm hardware to see if they actually work and/or their tests pass.

I have a branch `npm-feed` where I started a spike of the status service. All of this is up for review and change. If you've got a different idea you'd like to try to get the job done, lets take a look at that too.

cc @soldair

**Comment by Student007** [comment]
- [ ] Document how it works in the README.md

@reconbot I put my two cents in [here](https://github.com/tessel/t2-compiler/issues/20) :smile:

**Comment by Student007** [comment]
- [ ] The progress report / state - a list of state and comments about what is necessary to do to make a special package work. Also it should link related discussions.

**Comment by reconbot** [comment]
Today I updated our "cross compiler" to decouple it from vagrant and add docker support. We now have an image that will cross compile package binaries. For those not so familiar with docker, it lets us treat the whole "VM" as a single command. It works and it will run anywhere we host our server. (unlike vagrant) It also has the advantage of being disposable, each package build is isolated from the next and from the host system. This negates a possible security problem (hacking build servers through gypfiles).

Both the vagrant and docker `compile` commands use the same core script. I recommend we use docker as it's quicker to use and setup, but there's a low overhead maintaining both.

Now we that we have a "command" that produces compiled packages, the build server will be much easier to build.
